import io
import json
from docx import Document as DocxDocument
from typing import Dict

class ExportService:
    @staticmethod
    def to_markdown(mom: Dict) -> str:
        """Converts MoM JSON data into neat Markdown text."""
        md = []
        md.append(f"# Minutes of Meeting: {mom.get('title', 'Meeting Summary')}")
        md.append(f"**Date:** {mom.get('date', 'N/A')}  ")
        md.append(f"**Generated by:** InsightOrion  \n")
        
        md.append("## Executive Summary")
        md.append(f"{mom.get('executive_summary', 'No summary generated.')}\n")
        
        md.append("## Agenda Covered")
        for agenda in mom.get("agenda_covered", []):
            md.append(f"- {agenda}")
        md.append("")

        md.append("## Key Discussion Points")
        for point in mom.get("key_discussion_points", []):
            md.append(f"### {point.get('topic')}")
            md.append(f"{point.get('summary')}\n")
            
        md.append("## Decisions Made")
        for decision in mom.get("decisions_made", []):
            md.append(f"- {decision}")
        md.append("")

        md.append("## Action Items")
        md.append("| Task | Assignee | Priority | Due Date | Description |")
        md.append("| :--- | :--- | :--- | :--- | :--- |")
        for action in mom.get("action_items", []):
            md.append(f"| {action.get('title')} | {action.get('assignee_email')} | {action.get('priority')} | {action.get('due_date')} | {action.get('description')} |")
        md.append("")

        md.append("## Risks & Blocker Dependencies")
        for risk in mom.get("risks", []):
            md.append(f"- **Risk:** {risk.get('description')}")
            md.append(f"  - **Dependency:** {risk.get('dependency')}")
            md.append(f"  - **Escalation Plan:** {risk.get('escalation')}")
        md.append("")

        md.append("## Open Questions")
        for q in mom.get("open_questions", []):
            md.append(f"- {q}")
        md.append("")

        md.append("## Next Meeting Suggestions")
        sug = mom.get("next_meeting_suggestions", {})
        md.append(f"**Recommended Agenda:** {', '.join(sug.get('agenda', []))}")
        md.append(f"**Recommended Participants:** {', '.join(sug.get('recommended_participants', []))}")
        
        return "\n".join(md)

    @staticmethod
    def to_html(mom: Dict) -> str:
        """Converts MoM JSON data into styled HTML."""
        markdown_content = ExportService.to_markdown(mom)
        # Convert simple markdown headers/lists to HTML for quick PDF printing
        html_body = markdown_content.replace("\n", "<br>")
        html = f"""
        <!DOCTYPE html>
        <html>
        <head>
            <meta charset="utf-8">
            <title>{mom.get('title')}</title>
            <style>
                body {{ font-family: 'Inter', sans-serif; color: #1e293b; padding: 40px; line-height: 1.6; max-width: 800px; margin: auto; }}
                h1 {{ color: #0f172a; border-bottom: 2px solid #e2e8f0; padding-bottom: 10px; }}
                h2 {{ color: #334155; margin-top: 30px; border-bottom: 1px solid #f1f5f9; padding-bottom: 5px; }}
                h3 {{ color: #475569; }}
                table {{ width: 100%; border-collapse: collapse; margin-top: 15px; }}
                th, td {{ border: 1px solid #cbd5e1; padding: 10px; text-align: left; }}
                th {{ background-color: #f8fafc; color: #334155; }}
                ul {{ padding-left: 20px; }}
                li {{ margin-bottom: 8px; }}
                .tag {{ display: inline-block; padding: 2px 8px; border-radius: 4px; font-size: 12px; font-weight: bold; }}
                .priority-high {{ background-color: #fee2e2; color: #991b1b; }}
                .priority-medium {{ background-color: #fef3c7; color: #92400e; }}
                .priority-low {{ background-color: #dcfce7; color: #166534; }}
            </style>
        </head>
        <body>
            <h1>Minutes of Meeting: {mom.get('title')}</h1>
            <p><strong>Date:</strong> {mom.get('date')} &nbsp;&nbsp;|&nbsp;&nbsp; <strong>Generated by:</strong> InsightOrion</p>
            
            <h2>Executive Summary</h2>
            <p>{mom.get('executive_summary')}</p>
            
            <h2>Agenda Covered</h2>
            <ul>
                {"".join([f"<li>{a}</li>" for a in mom.get('agenda_covered', [])])}
            </ul>
            
            <h2>Key Discussion Points</h2>
            {"".join([f"<h3>{p.get('topic')}</h3><p>{p.get('summary')}</p>" for p in mom.get('key_discussion_points', [])])}
            
            <h2>Decisions Made</h2>
            <ul>
                {"".join([f"<li>{d}</li>" for d in mom.get('decisions_made', [])])}
            </ul>
            
            <h2>Action Items</h2>
            <table>
                <tr>
                    <th>Task</th>
                    <th>Assignee</th>
                    <th>Priority</th>
                    <th>Due Date</th>
                </tr>
                {"".join([f"<tr><td><strong>{a.get('title')}</strong><br>{a.get('description')}</td><td>{a.get('assignee_email')}</td><td>{a.get('priority')}</td><td>{a.get('due_date')}</td></tr>" for a in mom.get('action_items', [])])}
            </table>
            
            <h2>Risks & Dependencies</h2>
            <ul>
                {"".join([f"<li><strong>Risk:</strong> {r.get('description')}<br><small>Dependency: {r.get('dependency')} | Escalation: {r.get('escalation')}</small></li>" for r in mom.get('risks', [])])}
            </ul>
            
            <h2>Open Questions</h2>
            <ul>
                {"".join([f"<li>{q}</li>" for q in mom.get('open_questions', [])])}
            </ul>
        </body>
        </html>
        """
        return html

    @staticmethod
    def to_docx(mom: Dict) -> io.BytesIO:
        """Generates a downloadable DOCX binary file stream."""
        doc = DocxDocument()
        doc.add_heading(mom.get("title", "Minutes of Meeting"), level=0)
        doc.add_paragraph(f"Date: {mom.get('date')} | Generated by InsightOrion")

        # Executive Summary
        doc.add_heading("Executive Summary", level=1)
        doc.add_paragraph(mom.get("executive_summary", ""))

        # Agenda
        doc.add_heading("Agenda Covered", level=1)
        for agenda in mom.get("agenda_covered", []):
            doc.add_paragraph(agenda, style="List Bullet")

        # Discussion
        doc.add_heading("Key Discussion Points", level=1)
        for point in mom.get("key_discussion_points", []):
            doc.add_heading(point.get("topic", "Topic"), level=2)
            doc.add_paragraph(point.get("summary", ""))

        # Decisions
        doc.add_heading("Decisions Made", level=1)
        for d in mom.get("decisions_made", []):
            doc.add_paragraph(d, style="List Bullet")

        # Action Items Table
        doc.add_heading("Action Items", level=1)
        table = doc.add_table(rows=1, cols=4)
        hdr_cells = table.rows[0].cells
        hdr_cells[0].text = 'Task'
        hdr_cells[1].text = 'Owner'
        hdr_cells[2].text = 'Priority'
        hdr_cells[3].text = 'Due Date'

        for item in mom.get("action_items", []):
            row_cells = table.add_row().cells
            row_cells[0].text = item.get("title", "")
            row_cells[1].text = item.get("assignee_email", "")
            row_cells[2].text = item.get("priority", "MEDIUM")
            row_cells[3].text = item.get("due_date", "")

        # Save to buffer
        file_stream = io.BytesIO()
        doc.save(file_stream)
        file_stream.seek(0)
        return file_stream
